### ISSUE TITLE
permute_indices() function returns early

### ISSUE THREAD

**Issue by narodnik** [ETHorHIL/Plonk_TH#1]
```py
def permute_idices(wires):
    # This function takes an array "circuit" of arbitrary values and returns an
    # array with shuffles the indices of "circuit" for repeating values
    size = len(wires)
    permutation = [i + 1 for i in range(size)]
    for i in range(size):
        for j in range(i + 1, size):
            if wires[i] == wires[j]:
                permutation[i], permutation[j] = permutation[j], permutation[i]
                break
        return permutation
```

Looks like the return should be unindented.

**Comment by narodnik** [comment]
When I make the correction, I get the correct permutations of my wire values but then the prover exits with this error:
```py
Starting Round 3...
Traceback (most recent call last):
  File "Plonk_Py/plonk.py", line 87, in <module>
    test_plonk()
  File "Plonk_Py/plonk.py", line 81, in test_plonk
    proof_SNARK, u = prover_algo(witness, CRS, Qs, p_i_poly, perm_prep)
  File "Plonk_Py/prover.py", line 218, in prover_algo
    t_hi_eval_exp = evaluate_in_exponent(CRS, t_hi)
  File "Plonk_Py/prover.py", line 25, in evaluate_in_exponent
    assert poly.degree() < len(powers_of_tau)
AssertionError
```

**Comment by ethorhil** [comment]
@narodnik thanks so much for trying to run this code. It took me a while but I found the bug(s) now. Please try again, it does work now with the correction above.
